nb_webapp/urls.py
__author__ = 'jinguangzhou'
from django.conf.urls import patterns, url

from nb_webapp import views

urlpatterns = patterns('',
                       url(r'^$', views.IndexView.as_view(), name='index'),
                       #url(r'^register/$', views.RegisterView.as_view(), name='Sign up'),
                       url(r'^register/$', views.register, name='Register'),
                       url(r'^informationFromFriends', views.flowingInfo, name='flowingInfo'),
                       url(r'^login_signup', views.loginsignup, name = 'loginsignup'),
                       url(r'^login', views.login, name = 'login'),
                       url(r'^signup', views.signup, name = 'signup'),
)

noahboard/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from nb_webapp import views
admin.autodiscover()

urlpatterns = patterns('',
     url(r'^admin/', include(admin.site.urls)),
     url(r'^nb_webapp/', include('nb_webapp.urls', namespace="nb_webapp")),
)

templates/Temp/informationFormFriends.html
<!DOCTYPE html>
<html>
<head>
    <title>Personal Homepage</title>
</head>
<body>
friends lastest information:<br>
<ul>
    {% for key,value in FollowingDict.items %}
         {{ key }}-name:{{ value.last_name }}-{{ value.first_name }}:<br>
         {% for k,v in CardsDict.items%}
             {% ifequal key k %}
                {% for card in v %}
                   title: {{ card.title }}--Containt:{{ card.contents }}
                   <br>
                 {% endfor %}
             {% endifequal %}
         {% endfor %}
    {% endfor %}
</ul>
</body>
</html>

templates/Temp/login.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>

</body>
</html>

templates/Temp/loginsignup.html
<!DOCTYPE html>
<html>
<head>
    <title>Sign up and Log in</title>
</head>

<body>
    <form>
        {% csrf_token %}
        <p>Email Address: <input type="text" name="account_email"/></p>
        <p>Password: <input type = "password" name="password"/></p>
        <input type="submit" name="Sign up" value="sign_up" formaction="{% url 'nb_webapp:signup' %}" formmethod="post"/>
        <input type="submit" name="Log in" value = "login" formaction="{% url 'nb_webapp:login' %}" formmethod="post"/>
    </form>
</body>
</html>

templates/Temp/post.html
<!DOCTYPE html>
<html>
<head>
    <title>Post a new Knowledge Card</title>
</head>
<body>
    <form action="{% url 'post'  %}" method="post">
        {% csrf_token %}
        <p>title:  <input type="text" name="title"/></p>
        <p>contents: <input type = "text" name="contents"/></p>
        <p>video_link: <input tpe = "url" name="video_link"></p>
        <p>source_link: <input type = "url" name="source_link"></p>
        <p>tags: <input type = "text" name="tags"></p>
        <input type="submit" name="submit" value="submit"/>
    </form>
</body>
</html>

templates/Temp/signup.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>

</body>
</html>

templates/Temp/signup_result.html
<!DOCTYPE html>
<html>
<head>
    <title>Sign up result</title>
</head>
<body>
    <p>{{ sign_up_message }}</p>
</body>

</html>